name: RustDesk Windows Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: Windows

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive  # Самый простой способ - встроенная опция checkout

    - name: Build Windows
      run: ./wv.build.bat
      shell: powershell